import { defineConfig } from 'vitepress';

/**
 * Lanes, not a flat tree.
 *
 * Ten sidebar groups matching the ten cards on the landing page: a reader picks
 * a lane on the home page and the sidebar keeps them in it. Derived from the
 * product's shipped routes rather than from a topic list, which is how my-tasks,
 * webhooks, reports and documents earned places.
 */
export default defineConfig({
  title: 'Exto Docs',
  description: 'Build modules, forms and workflows — and follow a record through them.',
  cleanUrls: true,
  lastUpdated: true,
  themeConfig: {
    search: { provider: 'local' },
    /**
     * Nav mirrors Exto's own areas — commissioning, modules, building, setup,
     * administration — rather than generic activity labels. Recipes sits second
     * because a reader with a task in mind should never have to guess which
     * area owns it.
     */
    nav: [
      { text: 'Introduction', link: '/introduction' },
      { text: 'Recipes', link: '/recipes/' },
      { text: 'Commissioning', link: '/cx/' },
      { text: 'Modules', link: '/modules/' },
      { text: 'Designers', link: '/build/' },
      { text: 'Setup', link: '/setup/' },
      { text: 'Administering', link: '/admin/' },
      { text: 'Architecture', link: '/architecture/' },
    ],
    sidebar: {
      '/architecture/': [
        { text: 'Application architecture', collapsed: false, items: [
          { text: 'Overview', link: '/architecture/' },
          { text: 'The web client', link: '/architecture/web-client' },
          { text: 'API layers', link: '/architecture/api-layers' },
          { text: 'The data model', link: '/architecture/data-model' },
          { text: 'The form engine', link: '/architecture/form-engine' },
          { text: 'The workflow engine', link: '/architecture/workflow-engine' },
          { text: 'Records & audit', link: '/architecture/records-and-audit' },
        ] },
        { text: 'Feature architecture', collapsed: false, items: [
          { text: 'Module designer', link: '/architecture/module-designer' },
          { text: 'CX designer', link: '/architecture/cx-designer' },
          { text: 'CX execution', link: '/architecture/cx-execution' },
          { text: 'The AI platform', link: '/architecture/ai-platform' },
        ] },
      ],
      '/': [
      { text: 'Getting started', collapsed: false, items: [
        { text: 'Introduction', link: '/introduction' },
        { text: 'Overview', link: '/getting-started/' },
        { text: 'Quick start', link: '/getting-started/quick-start' },
        { text: 'Your first module', link: '/getting-started/first-module' },
        { text: 'Your first workflow', link: '/getting-started/first-workflow' },
      ] },
      { text: 'Core concepts', collapsed: true, items: [
        { text: 'Overview', link: '/concepts/' },
        { text: 'Modules & records', link: '/concepts/modules-and-records' },
        { text: 'Workflows & versions', link: '/concepts/workflows-and-versions' },
        { text: 'Permissions', link: '/concepts/permissions' },
        { text: 'Projects & spaces', link: '/concepts/projects-and-spaces' },
        { text: 'Masters', link: '/concepts/masters' },
      ] },
      { text: 'Modules & masters', collapsed: true, items: [
        { text: 'Modules', link: '/modules/' },
        { text: 'The life of a record', link: '/modules/record-lifecycle' },
        { text: 'Masters', link: '/masters/' },
        { text: 'Referencing a master', link: '/masters/referencing' },
        { text: 'Master data', link: '/work/masters' },
        { text: 'Hierarchical masters', link: '/work/hierarchical-masters' },
      ] },
      { text: 'Records & daily work', collapsed: true, items: [
        { text: 'Overview', link: '/work/' },
        { text: 'My tasks', link: '/work/my-tasks' },
        { text: 'Record list', link: '/work/record-list' },
        { text: 'Views', link: '/work/views' },
        { text: 'Record detail', link: '/work/record-detail' },
        { text: 'Record widgets', link: '/work/record-widgets' },
        { text: 'Taking actions', link: '/work/taking-actions' },
        { text: 'Workflow progress', link: '/work/workflow-progress' },
        { text: 'Editing in the grid', link: '/work/grid-editing' },
        { text: 'History', link: '/work/history' },
        { text: 'Importing & exporting', link: '/work/import-export' },
        { text: 'Documents', link: '/work/documents' },
        { text: 'Photos', link: '/work/photos' },
        { text: 'Reports', link: '/work/reports' },
        { text: 'Recycle bin & jobs', link: '/work/recycle-bin' },
      ] },
      { text: 'Commissioning (CX)', collapsed: true, items: [
        { text: 'Overview', link: '/cx/' },
        { text: 'Concepts', link: '/cx/concepts' },
        { text: 'Designing a workbench', link: '/cx/designer' },
        { text: 'Levels & stages', link: '/cx/levels-and-stages' },
        { text: 'Gates & dependencies', link: '/cx/gates' },
        { text: 'Stage templates', link: '/cx/stage-templates' },
        { text: 'The asset registry', link: '/cx/assets' },
        { text: 'Dates & scheduling', link: '/cx/dates' },
        { text: 'The commissioning matrix', link: '/cx/matrix' },
        { text: 'Completing a cell', link: '/cx/completing-a-cell' },
        { text: 'Documents', link: '/cx/documents' },
        { text: 'Handover', link: '/cx/handover' },
      ] },
      { text: 'Designers', collapsed: true, items: [
        { text: 'Overview', link: '/build/' },
        { text: 'Module designer', collapsed: true, items: [
          { text: 'The designer', link: '/build/module-designer' },
          { text: 'Module builder', link: '/build/module-builder' },
          { text: 'Forms', link: '/build/forms' },
          { text: 'Field types', link: '/build/field-types' },
          { text: 'Rules & validations', link: '/build/rules' },
          { text: 'Tables & data sets', link: '/build/tables-and-datasets' },
          { text: 'Reference tables', link: '/build/reference-tables' },
          { text: 'Log page views', link: '/build/log-page-views' },
          { text: 'Checklists', link: '/build/checklists' },
        ] },
        { text: 'Workflow designer', collapsed: true, items: [
          { text: 'Workflows', link: '/build/workflows' },
          { text: 'Steps & actions', link: '/build/steps-and-actions' },
          { text: 'Conditions', link: '/build/conditions' },
          { text: 'Publishing & versions', link: '/build/publishing' },
        ] },
        { text: 'Analytics designer', collapsed: true, items: [
          { text: 'Dashboards & reports', link: '/analytics/' },
          { text: 'Dashboards', link: '/analytics/dashboards' },
          { text: 'Dashboard setup', link: '/analytics/dashboard-setup' },
          { text: 'The dashboard builder', link: '/analytics/dashboard-builder' },
          { text: 'Report setup', link: '/analytics/report-setup' },
        ] },
      ] },
      { text: 'Setup & configuration', collapsed: true, items: [
        { text: 'Module setup', link: '/setup/' },
        { text: 'Deploying a module', link: '/setup/deploying' },
        { text: 'Access and owners', link: '/setup/access' },
        { text: 'Workflow step assignees', link: '/setup/step-assignees' },
        { text: 'Importing a module', link: '/setup/importing' },
        { text: 'Menu configuration', link: '/menu/' },
        { text: 'Building a menu', link: '/menu/building' },
        { text: 'Item types', link: '/menu/item-types' },
        { text: 'Activation', link: '/menu/activation' },
      ] },
      { text: 'Projects & access', collapsed: true, items: [
        { text: 'Overview', link: '/admin/' },
        { text: 'Projects', link: '/projects/' },
        { text: 'Workspaces', link: '/admin/workspaces' },
        { text: 'Projects & programs', link: '/admin/projects' },
        { text: 'Programs', link: '/projects/programs' },
        { text: 'Spaces', link: '/admin/spaces' },
        { text: 'Access control', link: '/access/' },
        { text: 'Users', link: '/admin/users' },
        { text: 'Groups & permissions', link: '/admin/groups' },
        { text: 'Stage configurations', link: '/access/stage-configurations' },
        { text: 'Settings', link: '/admin/settings' },
        { text: 'Data setup', link: '/admin/data-setup' },
      ] },
      { text: 'Integrations', collapsed: true, items: [
        { text: 'Overview', link: '/integrations/' },
        { text: 'External services', link: '/integrations/external-services' },
        { text: 'Webhooks', link: '/integrations/webhooks' },
      ] },
      { text: 'AI', collapsed: true, items: [
        { text: 'Overview', link: '/ai/' },
        { text: 'Using AI', items: [
          { text: 'Assistant', link: '/ai/assistant' },
          { text: 'Context & scope', link: '/ai/context' },
          { text: 'Attachments & documents', link: '/ai/attachments' },
          { text: 'Memory', link: '/ai/memory' },
          { text: 'CX workbench AI', link: '/ai/cx' },
          { text: 'Insights', link: '/ai/insights' },
          { text: 'AI form builder', link: '/ai/form-builder' },
        ] },
        { text: 'How it works', items: [
          { text: 'The reasoning loop', link: '/ai/reasoning-loop' },
          { text: 'Grounding & retrieval', link: '/ai/grounding' },
          { text: 'Guardrails & permissions', link: '/ai/guardrails' },
          { text: 'Limits, tracing & failure states', link: '/ai/operations' },
        ] },
      ] },
      { text: 'Your account', collapsed: true, items: [
        { text: 'Signing in', link: '/account/signing-in' },
        { text: 'Choosing a tenant', link: '/account/tenants' },
        { text: 'Your profile', link: '/account/profile' },
      ] },
      { text: 'Recipes', collapsed: true, items: [
        { text: 'All recipes', link: '/recipes/' },
        { text: 'Getting my work done', collapsed: true, items: [
          { text: 'Find the records waiting for me', link: '/recipes/work/find-my-work' },
          { text: 'Submit a record', link: '/recipes/work/submit-a-record' },
          { text: 'Approve or reject', link: '/recipes/work/approve-or-reject' },
          { text: 'Send back for changes', link: '/recipes/work/return-for-changes' },
          { text: 'Reopen a finished record', link: '/recipes/work/reopen-a-record' },
          { text: 'Request a revision', link: '/recipes/work/request-a-revision' },
          { text: 'Change who it is assigned to', link: '/recipes/work/change-assignees' },
          { text: 'Comment or mention someone', link: '/recipes/work/comment-and-mention' },
          { text: 'Attach a file or photo', link: '/recipes/work/attach-a-file' },
          { text: 'See what changed', link: '/recipes/work/see-what-changed' },
        ] },
        { text: 'Working faster', collapsed: true, items: [
          { text: 'Save a view', link: '/recipes/work/save-a-view' },
          { text: 'Edit many records at once', link: '/recipes/work/edit-many-records' },
          { text: 'Export what I see', link: '/recipes/work/export-a-grid' },
          { text: 'Restore something deleted', link: '/recipes/work/restore-deleted' },
        ] },
        { text: 'Reference data', collapsed: true, items: [
          { text: 'Add a master row', link: '/recipes/data/add-master-row' },
          { text: 'Import master data', link: '/recipes/data/import-master-data' },
          { text: 'Fix a failed import', link: '/recipes/data/fix-a-failed-import' },
          { text: 'Move an item in a hierarchy', link: '/recipes/data/move-in-hierarchy' },
        ] },
        { text: 'Commissioning', collapsed: true, items: [
          { text: 'Add an asset', link: '/recipes/cx/add-an-asset' },
          { text: 'Import an asset register', link: '/recipes/cx/import-assets' },
          { text: 'Set stage dates', link: '/recipes/cx/set-stage-dates' },
          { text: 'Enter dates in bulk', link: '/recipes/cx/bulk-dates' },
          { text: 'Complete a checklist', link: '/recipes/cx/complete-a-checklist' },
          { text: "Why a stage won't close", link: '/recipes/cx/stage-wont-close' },
          { text: 'Attach evidence', link: '/recipes/cx/attach-evidence' },
          { text: 'Generate a handover package', link: '/recipes/cx/generate-handover' },
          { text: 'Download several packages', link: '/recipes/cx/bulk-handover' },
        ] },
        { text: 'Building something new', collapsed: true, items: [
          { text: 'Create a module', link: '/recipes/build/create-a-module' },
          { text: 'Turn a paper form digital', link: '/recipes/build/from-paper-form' },
          { text: 'Add a field', link: '/recipes/build/add-a-field' },
          { text: 'Conditionally require a field', link: '/recipes/build/conditional-field' },
          { text: 'Block bad data', link: '/recipes/build/add-a-validation' },
          { text: 'Add a workflow step', link: '/recipes/build/add-a-workflow-step' },
          { text: 'Change a live workflow', link: '/recipes/build/change-a-live-workflow' },
          { text: 'Add a column to the list', link: '/recipes/build/add-a-column' },
          { text: 'Turn history on', link: '/recipes/build/turn-on-history' },
        ] },
        { text: 'Giving people access', collapsed: true, items: [
          { text: 'Grant access to a module', link: '/recipes/admin/grant-module-access' },
          { text: 'Add someone to a project', link: '/recipes/admin/add-to-project' },
          { text: "Why someone can't see something", link: '/recipes/admin/diagnose-access' },
          { text: 'Let someone see all records', link: '/recipes/admin/view-all-records' },
          { text: 'Add a page to the menu', link: '/recipes/admin/add-menu-item' },
          { text: 'Set a landing page', link: '/recipes/admin/set-landing-page' },
        ] },
        { text: 'AI & integrations', collapsed: true, items: [
          { text: 'Turn AI on', link: '/recipes/integrations/turn-on-ai' },
          { text: 'Teach it our terminology', link: '/recipes/integrations/curate-schema' },
          { text: 'Call another system', link: '/recipes/integrations/call-another-system' },
          { text: 'Notify another system', link: '/recipes/integrations/notify-another-system' },
          { text: 'Debug a webhook', link: '/recipes/integrations/debug-a-webhook' },
        ] },
        { text: 'My account', collapsed: true, items: [
          { text: 'Sign in', link: '/recipes/account/sign-in' },
          { text: 'Switch tenant', link: '/recipes/account/switch-tenant' },
          { text: 'Change the theme', link: '/recipes/account/change-theme' },
          { text: 'Change date format', link: '/recipes/account/change-date-format' },
          { text: 'Turn off AI insights', link: '/recipes/account/turn-off-insights' },
        ] },
        { text: 'Longer walkthroughs', collapsed: true, items: [
          { text: 'An approval workflow', link: '/recipes/approval-workflow' },
          { text: 'Onboarding a project team', link: '/recipes/onboard-a-team' },
          { text: 'Connecting an external system', link: '/recipes/connect-a-system' },
          { text: "Diagnosing \'I can\'t see it\'", link: '/recipes/cant-see-it' },
        ] },
      ] },
      ],
    },
  },
});
